=== uo295341/F1Desktop/xml/circuito.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://www.uniovi.es" elementFormDefault="qualified" targetNamespace="http://www.uniovi.es" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="circuitos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="circuito" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="fecha" />
				<xs:element ref="hora" />
				<xs:element ref="largo" />
				<xs:element ref="anchura" />
				<xs:element ref="vueltas" />
				<xs:element ref="localidad" />
				<xs:element ref="pais" />
				<xs:element ref="bibliografia" />
				<xs:element ref="multimedia" />
				<xs:element ref="coordenadas" />
			</xs:sequence>
			<xs:attribute name="nombre" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="fecha" type="xs:date" />
	<xs:element name="hora" type="xs:time" />
	<xs:element name="largo">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:integer">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="anchura">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:integer">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="vueltas" type="xs:integer" />
	<xs:element name="localidad" type="xs:string" />
	<xs:element name="pais" type="xs:string" />
	<xs:element name="bibliografia">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="url" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="url" type="xs:string" />
	<xs:element name="multimedia">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="imagenes" />
				<xs:element ref="videos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="imagenes">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="imagen" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="imagen" type="xs:string" />
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video" type="xs:string" />
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="centro" />
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="puntos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="centro">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="altitud" />
				<xs:element ref ="longitud"/>
				<xs:element ref="latitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="altitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="altitud">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="longitud">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="latitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="latitud">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="puntos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitudTramo" />
				<xs:element ref="puntoFinal" />
				<xs:element ref="numero" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitudTramo">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:integer">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="puntoFinal">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="altitudPunto" />
				<xs:element ref="longitudPunto" />
				<xs:element ref="latitudPunto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="altitudPunto">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="altitud">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="altitud">
		<xs:restriction base="xs:float">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="5000"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="longitudPunto">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="longitud">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="longitud">
		<xs:restriction base="xs:float">
			<xs:minInclusive value="-180"/>
			<xs:maxInclusive value="180"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="latitudPunto">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="latitud">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="latitud">
		<xs:restriction base="xs:float">
			<xs:minInclusive value="-90"/>
			<xs:maxInclusive value="90"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="numero" type="xs:integer" />
</xs:schema>

=== uo295341/F1Desktop/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuitos xmlns="http://www.uniovi.es"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.uniovi.es circuito.xsd">
    <circuito nombre="Las Vegas Strip Circuit">
        <fecha>2024-11-23</fecha>
        <hora>07:00:00</hora>
        <largo unidad="metros">6201</largo>
        <anchura unidad="metros">10</anchura>
        <vueltas>50</vueltas>
        <localidad>Las Vegas</localidad>
        <pais>Estados Unidos</pais>
        <bibliografia>
            <url>https://www.formula1.com/en/racing/2024/las-vegas/circuit</url>
            <url>https://www.mclaren.com/racing/formula-1/2024/las-vegas-grand-prix/</url>
            <url>https://www.redbull.com/es-es/circuito-las-vegas-f1-guia</url>
        </bibliografia>
        <multimedia>
            <imagenes>
                <imagen>LayoutTrack.jpg</imagen>
                <imagen>Panoramica.jpg</imagen>
                <imagen>Salida.jpg</imagen>
            </imagenes>
            <videos>
                <video>RaceHighLight.mp4</video>
            </videos>
        </multimedia>
        <coordenadas>
            <centro>
                <altitud unidad="metros">637</altitud>
                <longitud unidad="grados">-115.162219</longitud>
                <latitud unidad="grados">36.109017</latitud>
            </centro>
            <puntos>
                <longitudTramo unidad="metros">236</longitudTramo>
                <puntoFinal>
                    <sector>1</sector>
                    <altitudPunto unidad="metros">637</altitudPunto>
                    <longitudPunto unidad="grados">-115.162219</longitudPunto>
                    <latitudPunto unidad="grados">36.109017</latitudPunto>
                </puntoFinal>
                <numero>1</numero>
            </puntos>
            <puntos>
                <longitudTramo unidad="metros">25</longitudTramo>
                <puntoFinal>
                    <sector>1</sector>
                    <altitudPunto unidad="metros">634</altitudPunto>
                    <longitudPunto unidad="grados">-115.160217</longitudPunto>
                    <latitudPunto unidad="grados">36.110399</latitudPunto>
                </puntoFinal>
                <numero>2</numero>
            </puntos>
            <puntos>
                <longitudTramo unidad="metros">92</longitudTramo>
                <puntoFinal>
                    <sector>1</sector>
                    <altitudPunto unidad="metros">631</altitudPunto>
                    <longitudPunto unidad="grados">-115.160459</longitudPunto>
                    <latitudPunto unidad="grados">36.110517</latitudPunto>
                </puntoFinal>
                <numero>3</numero>
            </puntos>
            <puntos>
                <longitudTramo unidad="metros">199</longitudTramo>
                <puntoFinal>
                    <sector>1</sector>
                    <altitudPunto unidad="metros">631</altitudPunto>
                    <longitudPunto unidad="grados">-115.161489</longitudPunto>
                    <latitudPunto unidad="grados">36.110472</latitudPunto>
                </puntoFinal>
                <numero>4</numero>
            </puntos>
            <puntos>
                <longitudTramo unidad="metros">67</longitudTramo>
                <puntoFinal>
                    <sector>1</sector>
                    <altitudPunto unidad="metros">639</altitudPunto>
                    <longitudPunto unidad="grados">-115.163698</longitudPunto>
                    <latitudPunto unidad="grados">36.110252</latitudPunto>
                </puntoFinal>
                <numero>5</numero>
            </puntos>
            <puntos>
                <longitudTramo unidad="metros">927</longitudTramo>
                <puntoFinal>
                    <sector>1</sector>
                    <altitudPunto unidad="metros">635</altitudPunto>
                    <longitudPunto unidad="grados">-115.163981</longitudPunto>
                    <latitudPunto unidad="grados">36.110815</latitudPunto>
                </puntoFinal>
                <numero>6</numero>
            </puntos>
            <puntos>
                <longitudTramo unidad="metros">17</longitudTramo>
                <puntoFinal>
                    <sector>1</sector>
                    <altitudPunto unidad="metros">641</altitudPunto>
                    <longitudPunto unidad="grados">-115.164023</longitudPunto>
                    <latitudPunto unidad="grados">36.119152</latitudPunto>
                </puntoFinal>
                <numero>7</numero>
            </puntos>
            <puntos>
                <longitudTramo unidad="metros">356</longitudTramo>
                <puntoFinal>
                    <sector>1</sector>
                    <altitudPunto unidad="metros">641</altitudPunto>
                    <longitudPunto unidad="grados">-115.163838</longitudPunto>
                    <latitudPunto unidad="grados">36.119190</latitudPunto>
                </puntoFinal>
                <numero>8</numero>
            </puntos>
            <puntos>
                <longitudTramo unidad="metros">40</longitudTramo>
                <puntoFinal>
                    <sector>2</sector>
                    <altitudPunto unidad="metros">637</altitudPunto>
                    <longitudPunto unidad="grados">-115.160557</longitudPunto>
                    <latitudPunto unidad="grados">36.120991</latitudPunto>
                </puntoFinal>
                <numero>9</numero>
            </puntos>
            <puntos>
                <longitudTramo unidad="metros">103</longitudTramo>
                <puntoFinal>
                    <sector>2</sector>
                    <altitudPunto unidad="metros">637</altitudPunto>
                    <longitudPunto unidad="grados">-115.160853</longitudPunto>
                    <latitudPunto unidad="grados">36.121263</latitudPunto>
                </puntoFinal>
                <numero>10</numero>
            </puntos>
            <puntos>
                <longitudTramo unidad="metros">302</longitudTramo>
                <puntoFinal>
                    <sector>2</sector>
                    <altitudPunto unidad="metros">637</altitudPunto>
                    <longitudPunto unidad="grados">-115.160735</longitudPunto>
                    <latitudPunto unidad="grados">36.122189</latitudPunto>
                </puntoFinal>
                <numero>11</numero>
            </puntos>
            <puntos>
                <longitudTramo unidad="metros">248</longitudTramo>
                <puntoFinal>
                    <sector>2</sector>
                    <altitudPunto unidad="metros">636</altitudPunto>
                    <longitudPunto unidad="grados">-115.164089</longitudPunto>
                    <latitudPunto unidad="grados">36.122386</latitudPunto>
                </puntoFinal>
                <numero>12</numero>
            </puntos>
            <puntos>
                <longitudTramo unidad="metros">237</longitudTramo>
                <puntoFinal>
                    <sector>2</sector>
                    <altitudPunto unidad="metros">640</altitudPunto>
                    <longitudPunto unidad="grados">-115.166411</longitudPunto>
                    <latitudPunto unidad="grados">36.123607</latitudPunto>
                </puntoFinal>
                <numero>13</numero>
            </puntos>
            <puntos>
                <longitudTramo unidad="metros">536</longitudTramo>
                <puntoFinal>
                    <sector>2</sector>
                    <altitudPunto unidad="metros">633</altitudPunto>
                    <longitudPunto unidad="grados">-115.168065</longitudPunto>
                    <latitudPunto unidad="grados">36.125279</latitudPunto>
                </puntoFinal>
                <numero>14</numero>
            </puntos>
            <puntos>
                <longitudTramo unidad="metros">390</longitudTramo>
                <puntoFinal>
                    <sector>3</sector>
                    <altitudPunto unidad="metros">646</altitudPunto>
                    <longitudPunto unidad="grados">-115.171849</longitudPunto>
                    <latitudPunto unidad="grados">36.121548</latitudPunto>
                </puntoFinal>
                <numero>15</numero>
            </puntos>
            <puntos>
                <longitudTramo unidad="metros">382</longitudTramo>
                <puntoFinal>
                    <sector>3</sector>
                    <altitudPunto unidad="metros">656</altitudPunto>
                    <longitudPunto unidad="grados">-115.172890</longitudPunto>
                    <latitudPunto unidad="grados">36.117356</latitudPunto>
                </puntoFinal>
                <numero>16</numero>
            </puntos>
            <puntos>
                <longitudTramo unidad="metros">694</longitudTramo>
                <puntoFinal>
                    <sector>3</sector>
                    <altitudPunto unidad="metros">647</altitudPunto>
                    <longitudPunto unidad="grados">-115.173015</longitudPunto>
                    <latitudPunto unidad="grados">36.108714</latitudPunto>
                </puntoFinal>
                <numero>17</numero>
            </puntos>
            <puntos>
                <longitudTramo unidad="metros">74</longitudTramo>
                <puntoFinal>
                    <sector>3</sector>
                    <altitudPunto unidad="metros">673</altitudPunto>
                    <longitudPunto unidad="grados">-115.172383</longitudPunto>
                    <latitudPunto unidad="grados">36.108448</latitudPunto>
                </puntoFinal>
                <numero>18</numero>
            </puntos>
            <puntos>
                <longitudTramo unidad="metros">722</longitudTramo>
                <puntoFinal>
                    <sector>3</sector>
                    <altitudPunto unidad="metros">650</altitudPunto>
